### ISSUE TITLE
 when to release the code

### ISSUE THREAD

**Issue by Xuanmeng-Zhang** [speedinghzl/AlignSeg#1]
Dear author:
        Your work is excellent! I wonder when to release the code. Looking forward to your work!

**Comment by speedinghzl** [comment]
@Xuanmeng-Zhang  Thanks for your attention.  The code may be released in April because I'm busy finishing the thesis now.

**Comment by Qirui-Y** [comment]
@speedinghzl  Hello, I am very interested in your work, but I do not understand the alignment equation. How did you achieve it?

**Comment by ghost** [comment]
@speedinghzl  Hello, I am very interested in your work about the alignment equation .Could you provide source code?

**Comment by speedinghzl** [comment]
@stonessss @julyxia1992 Thanks for your interest in our work. I'm still busy with the doctoral dissertation and can not release the code on time. Sorry about that. The alignment function is based on bilinear interpolation function, with the help of learned offsets, the alignment function could control the position of sampling for alignment. It can be implemented with the grid_sample function in PyTorch. Hope the link helps. https://gist.github.com/peteflorence/a1da2c759ca1ac2b74af9a83f69ce20e

**Comment by adityac8** [comment]
Hi
Looking forward to the code release.

Thanks

**Comment by JamesLee789** [comment]
Dear Huang,
Your work looked awesome! Do you have any plan on releasing the code in the future? @speedinghzl Thanks!

**Comment by speedinghzl** [comment]
Hi all, thanks for waiting. The code and models are released.
