### ISSUE TITLE
 Aligned Feature Aggregation module differs from one mentioned in the article

### ISSUE THREAD

**Issue by h1063135843** [speedinghzl/AlignSeg#4]
![image](https://user-images.githubusercontent.com/26903569/120924930-bbd69480-c708-11eb-919b-809547d472e8.png)
Why CBA in your code have two delta_gens which get offset map separately? It is different from your article. Is it better?

**Comment by speedinghzl** [comment]
Yes, it is better. Due to the different scales (variances) of \delta^F and \delta^A, it is better to learn the two offsets separately.
