### ISSUE TITLE
what's means of RRB, CAM, CAB?

### ISSUE THREAD

**Issue by eeric** [speedinghzl/AlignSeg#5]
in alignseg.py

**Comment by speedinghzl** [comment]
Hi @eeric 
Names in the source code and in the [paper](https://arxiv.org/pdf/2003.00872.pdf) do not match up. There are corresponding relationships.

RRB -> Residual Convolutional Block
CAM -> Aligned Context Modeling
CAB -> Aligned Feature Aggregation

**Comment by eeric** [comment]
thank you very much
